"""initial schema

Revision ID: ee723b44b137
Revises: 
Create Date: 2026-08-25 13:18:51.649999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee723b44b137'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE orders SET status = 'pending' WHERE status IS NULL")
    op.execute("UPDATE orders SET status_updated_at = NOW() WHERE status_updated_at IS NULL")
    
    # Now alter columns to be NOT NULL
    op.alter_column('orders', 'status', nullable=False)
    op.alter_column('orders', 'status_updated_at', nullable=False)
    
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('idx_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stripe_session_id'), table_name='orders')
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'orders', ['stripe_session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_stripe_session_id_key', 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.create_index(op.f('ix_orders_stripe_session_id'), 'orders', ['stripe_session_id'], unique=True)
    op.create_index(op.f('idx_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('orders', 'status_updated_at')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
